# Author: George K. Holt
# License: MIT
"""
simulation.py
=============

Part of VISEPOCH.

Contains the Simulation class around which all analysis and plotting is
built.
"""
class Simulation:
    """Object describing an EPOCH LWFA simulation.

    Parameters
    ----------
    directory : str
        Path to EPOCH simulation directory, which should contain all of the SDF
        files generated by an EPOCH LWFA simulation.
    
    Attributes
    ----------
    directory : str
        Path to EPOCH simulation directory, which contains all of the SDF files
        generated by an EPOCH LWFA simulation.
    sim_files : list
        Ordered list of simulation dump file names of files in `directory`. Size
        ``N`` where ``N`` is the number of SDF files in `directory`.
    t : numpy ndarray
        1D array of ordered time values of the simulation dumps. Size ``N``
    electron_energy_avg_std : tuple
        2-tuple of 1D numpy ndarrays. The first array contains average electron
        ``high_gamma`` subset energies and the second contains the corresponding
        standard deviation of, both corresponding to `t` and of size ``N``.
        Initialised to ``None``. Populated by
        :meth:`visepoch.simulation.Simulation.calculate_electron_energy_avg_std`.
    electron_charge : numpy ndarray
        1D array of electron ``high_gamma`` subset charge measurements
        corresponding to `t` and of size ``N``. Initialised to ``None``.
        Populated by
        :meth:`visepoch.simulation.Simulation.calculate_electron_charge`.
    electron_energy_spectrum : tuple
        2-tuple containing the electron energy spectrum. First entry contains
        the energy bin edges. The second is a numpy ndarray containing the
        electron energy spectrum time size, of shape ``(len(bin_edges-1), N)``.
        Initialised to ``None``. Populated by
        :meth:`visepoch.simulation.Simulation.calculate_electron_energy_spectrum`.
    laser_a0 : numpy ndarray
        1D array of laser peak dimensionless laser amplitude measurements
        corresponding to `t` and of size ``N``. Initialised to ``None``.
        Populated by
        :meth:`visepoch.simulation.Simulation.calculate_laser_a0`.
    back_of_bubble_position : numpy ndarray
        1D array of x-position values of the back of the bubble. Initialised
        to ``None``. Populated by
        :meth:`visepoch.simulation.Simulation.calculate_back_of_bubble_position_velocity`.
    back_of_bubble_velocity : numpy ndarray
        1D array of x-velocity values of the back of the bubble. Initialised to
        ``None``. Populated by
        :meth:`visepoch.simulation.Simulation.calculate_back_of_bubble_position_velocity`.
    back_of_bubble_t_mid : numpy ndarray
        1D array of time values corresponding to the measurements of
        `back_of_bubble_velocity`. Initialise to ``None``. Populated by
        :meth:`visepoch.simulation.Simulation.calculate_back_of_bubble_position_velocity`.
    """
    
    from ._data import (
        datafiles,
        timestamps
    )
    
    from ._analyse import (
        calculate_electron_energy_avg_std,
        calculate_electron_charge,
        calculate_electron_energy_spectrum,
        calculate_laser_a0,
        calculate_back_of_bubble_position_velocity
    )
    from ._plot import (
        plot_electron_energy_avg_std,
        plot_electron_charge,
        plot_electron_energy_spectrum,
        plot_laser_a0,
        plot_back_of_bubble_helper,
        plot_back_of_bubble_velocity
    )
    
    def __init__(self, directory):
        
        self.directory = directory
        self.sim_files = self.datafiles(self.directory)
        self.t = self.timestamps(self.directory, self.sim_files)
        
        # electron beam measurements
        self.electron_energy_avg_std = None
        self.electron_charge = None
        self.electron_energy_spectrum = None
        
        # laser beam measurements
        self.laser_a0 = None
        
        # other measurements
        self.back_of_bubble_position = None
        self.back_of_bubble_velocity = None
        self.back_of_bubble_t_mid = None